[nixpacks]
node_version = "20"

[build]
install_command = "npm install --legacy-peer-deps"
build_command = "npx prisma generate && npm run build"
cache_disable = ["next", "node_modules", "tsconfig"]

[run]
start_command = "npm start"
